### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by zvin** [resin-io-modules/resin-register-device#31]

**Comment by zvin** [comment]
```
npm test

> resin-register-device@4.1.0 test /home/alexis/dev/resin.io/resin-register-device
> npm run lint && npm run test-node && npm run test-browser


> resin-register-device@4.1.0 lint /home/alexis/dev/resin.io/resin-register-device
> resin-lint lib tests gulpfile.coffee

  ⚡ lib/register.coffee
     ⚡ #27: Variable "getResinRegisterDevice" is assigned to but never read.
  ✓ tests/register.spec.coffee
  ✓ gulpfile.coffee

⚡ Warning! » 0 errors and 1 warning in 3 files


> resin-register-device@4.1.0 test-node /home/alexis/dev/resin.io/resin-register-device
> gulp test

[17:54:07] Failed to load external module coffeescript/register
[17:54:07] Requiring external module coffee-script/register
[17:54:07] Using gulpfile ~/dev/resin.io/resin-register-device/gulpfile.coffee
[17:54:07] Starting 'test'...
[17:54:08] 'test' errored after 119 ms
[17:54:08] TypeError in plugin 'gulp-mocha'
Message:
    getRequest._setFetch is not a function
Stack:
TypeError: getRequest._setFetch is not a function
    at Object.<anonymous> (/home/alexis/dev/resin.io/resin-register-device/tests/register.spec.coffee:13:12)
    at Object.<anonymous> (/home/alexis/dev/resin.io/resin-register-device/tests/register.spec.coffee:1:1)
    at Module._compile (module.js:635:30)
    at Object.loadFile (/home/alexis/dev/resin.io/resin-register-device/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/alexis/dev/resin.io/resin-register-device/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /home/alexis/dev/resin.io/resin-register-device/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>:null:null)
    at Mocha.loadFiles (/home/alexis/dev/resin.io/resin-register-device/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/alexis/dev/resin.io/resin-register-device/node_modules/mocha/lib/mocha.js:514:10)
    at Domain.<anonymous> (/home/alexis/dev/resin.io/resin-register-device/node_modules/gulp-mocha/index.js:56:20)
    at Domain.run (domain.js:242:14)
    at Stream.<anonymous> (/home/alexis/dev/resin.io/resin-register-device/node_modules/gulp-mocha/index.js:54:5)
    at _end (/home/alexis/dev/resin.io/resin-register-device/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/alexis/dev/resin.io/resin-register-device/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/home/alexis/dev/resin.io/resin-register-device/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at /home/alexis/dev/resin.io/resin-register-device/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)


npm ERR! Linux 4.10.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-node"
npm ERR! node v8.9.3
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! resin-register-device@4.1.0 test-node: `gulp test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the resin-register-device@4.1.0 test-node script 'gulp test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the resin-register-device package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs resin-register-device
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls resin-register-device
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alexis/dev/resin.io/resin-register-device/npm-debug.log
npm ERR! Test failed.  See above for more details.
```
